# Generated by Selenium IDE
import ssl
import time
import json
import unittest

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC
from Funciones.Funciones_Cobranza1 import Funciones_ModuloUNo
from selenium.webdriver.chrome.options import Options

class base_test(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()


    def test_reservaciones_sillas(self):
        driver=self.driver
        f=Funciones_ModuloUNo(driver)
        f.Open_Page("https://forms.office.com/pages/responsepage.aspx?id=2ua7Zek1GEyZO-4sFst-ZNqAzElf8tdMs1hvkR085LRUMDBBNElURzk0M1dGVTM5OUJWTVdVTThXRi4u", 5)
        f.Texto_ID_Validar_Click("i0116", "rrosa@veconinter.com", 3)
        f.Click_ID_Validar("idSIButton9", 3)
        f.Texto_ID_Validar_Click("i0118", "Ellynesca$1279", 3)
        f.Click_ID_Validar("idSIButton9", 2)
        f.Click_ID_Validar("idSIButton9", 5)
        f.Click_XPATH_Validar("//div[@id='form-main-content1']/div/button/div", 3)
        f.Click_XPATH_Validar("//*[@id='QuestionChoiceOption4']", 3)
        f.Check_XPATH("//*[@id='QuestionChoiceOption6']",3)
        #f.Click_XPATH_Validar("//*[@id='QuestionChoiceOption18']", 3)#puesto 1
        f.Click_XPATH_Validar("//*[@id='QuestionChoiceOption19']", 3) #puesto 2
        #f.Click_XPATH_Validar("//*[@id='QuestionChoiceOption20']", 3) #puesto 3
        #f.Click_XPATH_Validar("//*[@id='QuestionChoiceOption21']", 3) #puesto 4
        #f.Click_XPATH_Validar("//*[@id='QuestionChoiceOption25']", 3) #puesto 8
        #f.Click_XPATH_Validar("//*[@id='QuestionChoiceOption26']", 3) #puesto 9
        #f.Click_XPATH_Validar("//*[@id='QuestionChoiceOption27']", 3)#puesto 10
        time.sleep(3)

        f.Texto_XPATH_Validar_Click("(//input[contains(@aria-label,'Texto de una sola línea')])[1]", "evilchez@veconinter.com", 3)
        f.Texto_XPATH_Validar_Click("(//input[contains(@aria-label,'Texto de una sola línea')])[2]", "Edwar Vilchez",3)
        f.Click_XPATH_Validar("//i[contains(@data-icon-name,'Calendar')]",3)
        #f.Click_XPATH_Validar("(//td[@data-is-focusable='true'])[31]", 3)
        #f.Click_XPATH_Validar("//button[contains(@data-automation-id,'submitButton')]", 3)

        '''f.Open_Page("https://brematlocal.sharepoint.com/sites/Intranet",5)
        f.Texto_ID_Validar_Click("i0116", "rrosa@veconinter.com", 3)
        f.Click_ID_Validar("idSIButton9", 3)
        f.Texto_ID_Validar_Click("i0118", "Ellynesca$1279",3)
        f.Click_ID_Validar("idSIButton9", 2)
        f.Click_ID_Validar("idSIButton9", 5)

        mov1=driver.find_element(By.CSS_SELECTOR, ".ms-HorizontalNavItem:nth-child(6) .ms-HorizontalNavItem-linkText")
        #mov2 = driver.find_element(By.CSS_SELECTOR, ".ms-ContextualMenu-item:nth-child(2) .ms-ContextualMenu-itemText")
        act=ActionChains(driver)
        act.move_to_element(mov1).click().perform()
        time.sleep(5)

        mov2=driver.find_element(By.CSS_SELECTOR, ".ms-ContextualMenu-item:nth-child(2) .ms-ContextualMenu-itemText")
        act.move_to_element(mov2).click().perform()
        time.sleep(4)
        driver.execute_script("window.scrollTo(0, 600)")
        time.sleep(3)
        driver.switch_to.window(driver.window_handles[1])
        f.Click_ID_Validar("📍-piso-17", 4)
        driver.execute_script("window.scrollTo(0, 600)")
        f.Click_XPATH_Validar("//strong[contains(.,'Reservar Zona América del Norte')]", 4)
        f.Click_XPATH_Validar("//i[contains(@aria-describedby,'tooltip-31')]", 3)
        f.Click_XPATH_Validar("(//span[contains(.,'📝 Registrar Reservación')])[3]", 10)
        #driver.switch_to.window(driver.window_handles[2])
        f.Click_XPATH_Validar("//div[@id='form-main-content1']/div/button/div", 3)'''

    def tearDown(self):
        driver = self.driver
        driver.close()


if __name__== '__main__':
    unittest.main()