# Generated by Selenium IDE
import ssl
import time
import json
import pytest

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

from selenium.webdriver.chrome.options import Options

from Reservaciones_Page import Funciones_Reservaciones

#class base_test(unittest.TestCase):





'''def testuno_reservacion_sillas():

    driver = webdriver.Chrome()
    fr = Funciones_Reservaciones(driver)
    fr.Reservacion_Uno("rrosa@veconinter.com","Ellynesca$1279", "rrosa@veconinter.com", "Ronald De La Rosa")
    #fr.Reservacion_Dos("rrosa@veconinter.com", "Ellynesca$1279", "evilchez@veconinter.com", "Edwar Vilchez")
    #fr.Reservacion_Tres("rrosa@veconinter.com", "Ellynesca$1279", "Jalbornoz@veconinter.com", "Jacqueline Albornoz")
    #fr.Reservacion_Cuatro("rrosa@veconinter.com", "Ellynesca$1279", "yoliveros@veconinter.com", "Yotzy Oliveros")
    #fr.Reservacion_Ocho("rrosa@veconinter.com", "Ellynesca$1279", "mcrubio@veconinter.com", "Maria Claudia Rubio")
    #fr.Reservacion_Nueve("rrosa@veconinter.com", "Ellynesca$1279", "rllanos@veconinter.com", "Rommel Llanos")
    #fr.Reservacion_Diez("rrosa@veconinter.com", "Ellynesca$1279", "Pserrano@veconinter.com", "Patricia Serrano")'''

def testuno_reservacion_sillas():
    driver = webdriver.Chrome()
    fr = Funciones_Reservaciones(driver)
    fr.Reservacion_Uno("rrosa@veconinter.com", "Ellynesca$1279", "rrosa@veconinter.com", "Ronald De La Rosa")



def testdos_reservacion_sillas():
    driver = webdriver.Chrome()
    fr = Funciones_Reservaciones(driver)
    fr.Reservacion_Dos("rrosa@veconinter.com", "Ellynesca$1279", "evilchez@veconinter.com", "Edwar Vilchez")



def testtres_reservacion_sillas():
    driver = webdriver.Chrome()
    fr = Funciones_Reservaciones(driver)
    fr.Reservacion_Tres("rrosa@veconinter.com", "Ellynesca$1279", "Jalbornoz@veconinter.com", "Jacqueline Albornoz")


def testcuatro_reservacion_sillas():
    driver = webdriver.Chrome()
    fr = Funciones_Reservaciones(driver)
    fr.Reservacion_Cuatro("rrosa@veconinter.com", "Ellynesca$1279", "yoliveros@veconinter.com", "Yotzy Oliveros")

def testcinco_reservacion_sillas():
    driver = webdriver.Chrome()
    fr=Funciones_Reservaciones(driver)
    fr.Reservacion_Ocho("rrosa@veconinter.com", "Ellynesca$1279", "mcrubio@veconinter.com", "Maria Claudia Rubio")


def testseis_reservacion_sillas():
    driver = webdriver.Chrome()
    fr=Funciones_Reservaciones(driver)
    fr.Reservacion_Nueve("rrosa@veconinter.com", "Ellynesca$1279", "rllanos@veconinter.com", "Rommel Llanos")

def testsiete_reservacion_sillas():
    driver = webdriver.Chrome()
    fr=Funciones_Reservaciones(driver)
    fr.Reservacion_Diez("rrosa@veconinter.com", "Ellynesca$1279", "Pserrano@veconinter.com", "Patricia Serrano")

def testocho_reservacion_sillas():
    driver = webdriver.Chrome()
    fr=Funciones_Reservaciones(driver)
    fr.Reservacion_Cinco("rrosa@veconinter.com", "Ellynesca$1279", "jortega@veconinter.com", "jesus ortega")

def testnueve_reservacion_sillas():
    driver = webdriver.Chrome()
    fr=Funciones_Reservaciones(driver)
    fr.Reservacion_Seis("rrosa@veconinter.com", "Ellynesca$1279", "jalves@veconinter.com", "jonathan alves")

def testdiez_reservacion_sillas():
    driver = webdriver.Chrome()
    fr=Funciones_Reservaciones(driver)
    fr.Reservacion_Siete("rrosa@veconinter.com", "Ellynesca$1279", "eshernandez@veconinter.com", "esther hernandez")

def testonce_reservacion_sillas():
    driver = webdriver.Chrome()
    fr=Funciones_Reservaciones(driver)
    fr.Reservacion_Once("rrosa@veconinter.com", "Ellynesca$1279", "kmonsalve@veconinter.com", "Karen Monsalve")

def testdoce_reservacion_sillas():
    driver = webdriver.Chrome()
    fr=Funciones_Reservaciones(driver)
    fr.Reservacion_Doce("rrosa@veconinter.com", "Ellynesca$1279", "kzapata@veconinter.com", "kevin zapata")

def testtrece_reservacion_sillas():
    driver = webdriver.Chrome()
    fr=Funciones_Reservaciones(driver)
    fr.Reservacion_Trece("rrosa@veconinter.com", "Ellynesca$1279", "elozada@veconinter.com", "emerio lozada")





"""def tearDown(self):
        driver = self.driver
        driver.close()


if __name__== '__main__':
    #unittest.main()"""

